services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    volumes:
      - ../:/app
      - /app/node_m
    ports:
      - "4200:4200"
    command: npx ng serve --host 0.0.0.0 --poll 2000
